version: "3.8"

services:
  tenfellWebos:
    image: fs185085781/webos:latest
    container_name: tenfellWebos
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - "/var/apps/tenfellos/shares/tenfellos/rootPath:/webos/api/rootPath" #容器内系统文件映射
      - "/var/apps/tenfellos/shares/tenfellos/apps:/webos/web/apps" #插件持久化
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    shm_size: "1gb"
    network_mode: bridge
